site_name: pyp2spec
site_description: Generate valid Fedora RPM spec files from Python packages
site_url: https://pyp2spec.readthedocs.io/
site_author: Karolina Surma

repo_name: befeleme/pyp2spec
repo_url: https://github.com/befeleme/pyp2spec
edit_uri: edit/main/docs/

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - bash
    - toml
    - json

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Examples:
      - Basic Examples: examples/basic-packages.md
      - Custom Configuration: examples/custom-configuration.md
      - Automode: examples/automode.md
  - Contributing:
      - Development Setup: contributing/development-setup.md
  - Changelog: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/befeleme/pyp2spec
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pyp2spec/